[project]
name = "aula-04"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "annotated-doc",
    "annotated-types",
    "anyio",
    "certifi",
    "click",
    "distro",
    "fastapi",
    "h11",
    "httpcore",
    "httpx",
    "idna",
    "jiter",
    "openai",
    "pydantic",
    "pydantic_core",
    "python-multipart",
    "sniffio",
    "starlette",
    "tqdm",
    "typing-inspection",
    "typing_extensions",
    "uvicorn",
    "chromadb",
    "pypdf",
    "tiktoken",
    "onnxruntime<=1.23.1",
    "psutil"
]
